name: Manual Build Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
            lfs: true
  
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 16.17
  
      - name: Enable corepack
        run: corepack enable yarn
  
      - run: yarn install --immutable
  
      - name: Build prod files
        run: |
          yarn run desktop:build:prod
  
      - name: Build software
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            yarn run package:win
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            yarn run package:linux
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            yarn run package:darwin
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: |
            ./output/windows/*  # Adjust paths as per your build scripts
            ./output/ubuntu/*
            ./output/macos/*
