name: Manual Build Workflow

on:
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build prod files
      run: |
        yarn run desktop:build:prod

    - name: Build package
      run: |
        yarn run package:darwin
        
