name: Manual Build Workflow

on:
  workflow_dispatch:

jobs:
  build_on_mac:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          lfs: true

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 16.17
      - run: corepack enable yarn

      - run: yarn install --immutable
  
      - name: Build prod files
        run: |
          yarn run desktop:build:prod
  
      - name: Build package
        run: |
          yarn run package:darwin
