name: Post Release

# run after releases are published
on:
  release:
    types: [released]

jobs:
  bump:
    name: Echo release 
    runs-on: ubuntu-20.04

    permissions:
      contents: write
    
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
          with:
            lfs: true
  
        - name: Echo release version
          run: echo "v${{ github.event.release.tag_name }}"

  
      

