name: Post Release

# run after releases are published
on:
  release:
    types: [released]

jobs:
  bump:
    name: Echo runned
    runs-on: ubuntu-20.04

    steps:
      - name: Run echo
        run: echo "post-release Runned!"
