# .github/workflows/pre-build.yml
name: Pre-Build (Reusable)

on:
  workflow_call:
    inputs:
      version:
        description: 'The version to build'
        required: true
        type: string
      commit_sha:
        description: 'The commit SHA to checkout for the build'
        required: true
        type: string
    secrets:
      LICHTBLICK_GITHUB_TOKEN:
        description: 'PAT for checkout or other privileged operations'
        required: false

jobs:
  build:
    name: Pre-Build VERSION - ${{ inputs.version }} # Este é o nome de exibição do job, agora dinâmico.
    runs-on: macos-latest
    steps:
      - name: Checkout Repository at specific commit
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.LICHTBLICK_GITHUB_TOKEN || github.token }}
          ref: ${{ inputs.commit_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.17 # Ou a versão que o seu projeto necessita

      - name: Enable corepack
        run: corepack enable

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ inputs.commit_sha }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Set build version environment variable
        run: echo "BUILD_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Build prod files
        run: |
          yarn run desktop:build:prod

      - name: Build Windows version
        run: yarn run package:win

      - name: Build Linux version
        run: yarn run package:linux

      - name: Build macOS version
        run: yarn run package:darwin

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: lichtblick-${{ env.BUILD_VERSION }}-windows
          path: dist/lichtblick-${{ env.BUILD_VERSION }}-win.exe
          retention-days: 30

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: lichtblick-${{ env.BUILD_VERSION }}-debian-amd64
          path: dist/lichtblick-${{ env.BUILD_VERSION }}-linux-amd64.deb
          retention-days: 30

      - name: Upload MacOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: lichtblick-${{ env.BUILD_VERSION }}-macos
          path: dist/lichtblick-${{ env.BUILD_VERSION }}-mac-universal.dmg
          retention-days: 30
